### ISSUE TITLE
Resubmitted application still showing up

### ISSUE THREAD

**Issue by Subhash-Karri** [questbook/grants-frontend#124]
Reviewed an application and clicked asked to resubmit with more details.

https://www.loom.com/share/84038b9cd73844239b8c726de4a9462e

1. It's been 5 mins and after that, when I check my applications, this application is still 'Pending Review', which it shouldn't. I tried again to 'ask for resubmit' and it gives me a non-descriptive - 'Transaction failed' error message. Imagine, if I have to process 20-30 applications. There is no way, I can track which applications I have asked to resubmit and what exactly is the error.
2. When I ask the applicant to resubmit, how will they get notified? I am assuming you are not sending any email now. Discourse does a lot of notification easier and without such communication, our tool tends to be painful.

**Comment by AlwaysHungrie** [comment]
You need to reload the page to view the updated status. Right now it's not possible to have instant updates. The problem that came about state not updating probably came because of the problems with Rinkeby. The experience will be fixed once we implement optimistic loading. 


Please  reopen this issue  if it comes  up again  along with the transaction hash
